### ISSUE TITLE
Překlepy v číselníku Sporty

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/ciselniky#3]
(Požadavek z Českého Krumlova)
překlep: In-line bruselní
překlep: Fresbee (správně Frisbee)
překlep: Czcle polo
chybí Bruslení (na zimáku)
chybí Dopravní výuka (dopravní hřiště)
chybí Fitness
chybí Streetball
chybí Sportovní střelba

**Comment by dvoriik** [comment]
![image](https://user-images.githubusercontent.com/55543279/75119376-b4f65080-5682-11ea-858d-7e787d42d739.png)
@jakubklimek je třeba dělat fork? 
K výše uvedenému: překlepy jsem odstranil
Doplněno: bruslení, streetball
NEchybí: fitness, sportovní střelba
Dopravní výuku nepovažuji za sport

**Comment by jakubklimek** [comment]
Buďto fork, a nebo z každé změny udělat Pull request. Případně budeme moct udělat develop branch stejně jako u OFN

**Comment by jirkamarekbrno** [comment]
@jakubklimek takže udělat tu develop branch, aby nám šly ty pull requesty ne? Jinak to totiž z masteru do master nejde, ok?

**Comment by jakubklimek** [comment]
@jirkamarekbrno OK, hotovo
